var tools = [
	{image: "div.png"}, 
	{image: "undo.png", command: "undo", title: "Undo"},
	{image: "redo.png", command: "redo", title: "Redo"},
	{image: "format.png", command: "removeFormat", title: "Remove formatting"},
	{image: "div.png"}, 
	{image: "bold.png", command: "bold", title: "Bold"}, 
	{image: "italic.png", command: "italic", title: "Italic"}, 
	{image: "underline.png", command: "underline", title: "Underline"}, 
	{image: "div.png"}, 
	{image: "dottedlist.png", command: "insertunorderedlist", title: "Unordered List"}, 
	{image: "numberedlist.png", command: "insertorderedlist", title: "Ordered List"}, 
	{image: "div.png"},
	{image: "justifyleft.png", command: "justifyleft", title: "Left align"},
	{image: "justifycenter.png", command: "justifycenter", title: "Center align"},
	{image: "justifyright.png", command: "justifyright", title: "Right align"},
	{image: "div.png"},
	{image: "outdent.png", command: "outdent", title: "Delete indentation"},
	{image: "indent.png", command: "indent", title: "Add indentation"},
];